server:
  port: 50051
docker:
  host: unix:///var/run/docker.sock
  tls_cert_path: ''
  tls_verify: false
  api_version: ''
  network: default
  allow_connection_failure: true
resource:
  cpu: 2000
  memory: 2048Mi
  gpu: 7
resource_tags:
- cpu
- gpu
- memory
