server:
  port: 50059
kubernetes:
  kubeconfig: /root/.kube/config
  namespace: default
  in_cluster: false
  label_selector: iarnet.managed=true
  allow_connection_failure: true
resource:
  cpu: 4000
  memory: 4096Mi
  gpu: 1
resource_tags:
- cpu
- gpu
- memory
