server:
  port: 50081
kubernetes:
  kubeconfig: ''
  namespace: default
  in_cluster: true
  label_selector: iarnet.managed=true
  allow_connection_failure: true
resource:
  cpu: 4000
  memory: 4096Mi
  gpu: 5
resource_tags:
- camera
- cpu
- gpu
- memory
