server:
  port: 50054
kubernetes:
  kubeconfig: ''
  namespace: default
  in_cluster: true
  label_selector: iarnet.managed=true
  allow_connection_failure: true
resource:
  cpu: 4000
  memory: 4096Mi
  gpu: 0
resource_tags:
- cpu
- memory
